[package]
name = "windesheim_glade"
version = "0.1.0"
authors = ["CallidusU <bart1evers@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1.2.1"
csv = "1.1"
rand = "0.7.0"
